from django.urls import path
from home import views

urlpatterns = [
    path('' , views.index , name="index"),
    path('login/' , views.login_page, name='login_page'),
    path('register/' , views.register, name='register'),
    path('logout/' , views.logout_user, name='logout_user'),
    path('settings/' , views.customer_settings, name='customer_settings'),
    path('help/' , views.help, name='help'),
    # path('contactus/' , views.contactus, name='contactus'),
    path('aboutus/' , views.aboutus, name='aboutus'),
    path('services/' , views.services, name='services'),
    path('blog/' , views.blog, name='blog'),
    path('careers/' , views.careers, name='careers'),
    path('privacy-policy/' , views.privacy_policy, name='privacy_policy'),
    path('events/' , views.events, name='events'),
    path('distance-preview/', views.distance_preview, name='distance_preview'),
    path('ajax/live-state/', views.live_state, name='live_state'),
    path('ajax/home-order-widget/', views.home_order_widget_partial, name='home_order_widget_partial'),
    path('ajax/featured-dishes/', views.featured_dishes_partial, name='featured_dishes_partial'),
    path('ajax/shop-dishes/', views.shop_dishes_partial, name='shop_dishes_partial'),
    path('shop/' , views.shop, name='shop'),
    path('shop/add-to-cart/<int:dish_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_page, name='cart_page'),
    path('cart/remove/<int:dish_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/update/<int:dish_id>/', views.update_cart_quantity, name='update_cart_quantity'),
    path('cart/checkout/', views.checkout_cart, name='checkout_cart'),
    path('notifications/', views.notification_center, name='notification_center'),
    path('notifications/clear/', views.clear_notifications, name='clear_notifications'),
    path('orders/', views.past_orders, name='past_orders'),
    path('orders/remove/<int:order_id>/', views.remove_past_order, name='remove_past_order'),
    path('orders/cancel-recent/', views.cancel_recent_order_group, name='cancel_recent_order_group'),
    path('orders/cancel/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('orders/reorder/<int:order_id>/', views.reorder_order, name='reorder_order'),
    path('upi/single/<int:order_id>/', views.upi_payment_single, name='upi_payment_single'),
    path('upi/bulk/', views.upi_payment_bulk, name='upi_payment_bulk'),
    path('shop/checkout/<int:dish_id>/', views.checkout, name='checkout'),
    path('shop/order-success/<int:order_id>/', views.order_success, name='order_success'),
    path('shop/order-success/<int:order_id>/review/', views.submit_order_review, name='submit_order_review'),
    path('orders/<int:order_id>/dismiss-review-prompt/', views.dismiss_order_review_prompt, name='dismiss_order_review_prompt'),
    path('order-confirmation/', views.order_confirmation, name='order_confirmation'),
    path('newsletter/' , views.newsletter, name='newsletter'),

]
